id: P669EA080
initial_creation_type: input
source_metadata:
  Title: Buddhist Himalaya
  Editor: Shakya, M. B.
  Publisher: Nagarjuna Institute of Exact Methods
  Place of Publication: Nepal
  Year: '1988'
  Ārya advayaśatikā prajñāpāramitā sūtra:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:09:32.399254'
last_modified_at: '2022-03-08T16:09:32.399262'
